/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dostojic.climbers.view.form;

import com.dostojic.climbers.view.form.climber.PanelListClimbers;
import com.dostojic.climbers.view.form.util.FormActionHelper;
import com.dostojic.climbers.view.form.util.FormStyleHelper;
import com.dostojic.climbers.view.form.util.FrameDragListener;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.function.Consumer;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author planina
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        this.setUndecorated(true);
        initComponents();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        panelIconMinMaxClose = new javax.swing.JPanel();
        panelButtonMin = new javax.swing.JPanel();
        labelMinimize = new javax.swing.JLabel();
        panelButtonClose = new javax.swing.JPanel();
        labelClose = new javax.swing.JLabel();
        panelButtonMax = new javax.swing.JPanel();
        labelMaximize = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelMenuIcon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelBurger = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelSettings = new javax.swing.JLabel();
        panelMenuHide = new javax.swing.JPanel();
        panelMenuClimbers = new javax.swing.JPanel();
        panelClimbersMain = new javax.swing.JPanel();
        labelClimbersText = new javax.swing.JLabel();
        labelClimbersIcon = new javax.swing.JLabel();
        panelClimbersNew = new javax.swing.JPanel();
        labelClimbersText1 = new javax.swing.JLabel();
        labelClimbersIcon1 = new javax.swing.JLabel();
        panelClimbersSearch = new javax.swing.JPanel();
        labelClimbersText2 = new javax.swing.JLabel();
        labelClimbersIcon2 = new javax.swing.JLabel();
        panelMenuCompetition = new javax.swing.JPanel();
        panelCompetitonMain = new javax.swing.JPanel();
        labelClimbersText3 = new javax.swing.JLabel();
        labelClimbersIcon3 = new javax.swing.JLabel();
        panelCompetitonNew = new javax.swing.JPanel();
        labelClimbersText4 = new javax.swing.JLabel();
        labelClimbersIcon4 = new javax.swing.JLabel();
        panelCompetitonSearch = new javax.swing.JPanel();
        labelClimbersText5 = new javax.swing.JLabel();
        labelClimbersIcon5 = new javax.swing.JLabel();
        panelMainContent = new com.dostojic.climbers.view.form.PanelMainContent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        panelHeader.setBackground(new java.awt.Color(5, 10, 46));
        panelHeader.setPreferredSize(new java.awt.Dimension(800, 50));
        panelHeader.setLayout(new java.awt.BorderLayout());

        panelIconMinMaxClose.setBackground(new java.awt.Color(5, 10, 46));
        panelIconMinMaxClose.setPreferredSize(new java.awt.Dimension(150, 50));
        panelIconMinMaxClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButtonMin.setBackground(new java.awt.Color(5, 10, 46));
        panelButtonMin.setPreferredSize(new java.awt.Dimension(50, 50));
        panelButtonMin.setLayout(new java.awt.BorderLayout());

        labelMinimize.setBackground(new java.awt.Color(5, 10, 46));
        labelMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMinimize.setOpaque(true);
        panelButtonMin.add(labelMinimize, java.awt.BorderLayout.CENTER);

        panelIconMinMaxClose.add(panelButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelButtonClose.setBackground(new java.awt.Color(5, 10, 46));
        panelButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        panelButtonClose.setLayout(new java.awt.BorderLayout());

        labelClose.setBackground(new java.awt.Color(5, 10, 46));
        labelClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelClose.setOpaque(true);
        panelButtonClose.add(labelClose, java.awt.BorderLayout.CENTER);

        panelIconMinMaxClose.add(panelButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        panelButtonMax.setBackground(new java.awt.Color(5, 10, 46));
        panelButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));
        panelButtonMax.setLayout(new java.awt.BorderLayout());

        labelMaximize.setBackground(new java.awt.Color(5, 10, 46));
        labelMaximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMaximize.setOpaque(true);
        panelButtonMax.add(labelMaximize, java.awt.BorderLayout.CENTER);

        panelIconMinMaxClose.add(panelButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        panelHeader.add(panelIconMinMaxClose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelMenu.setPreferredSize(new java.awt.Dimension(270, 450));
        panelMenu.setLayout(new java.awt.BorderLayout());

        panelMenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        panelMenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        panelMenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 10, 46));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        labelBurger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labelBurger, java.awt.BorderLayout.CENTER);

        panelMenuIcon.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(5, 10, 46));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        labelSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(labelSettings, java.awt.BorderLayout.CENTER);

        panelMenuIcon.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        panelMenu.add(panelMenuIcon, java.awt.BorderLayout.LINE_START);

        panelMenuHide.setBackground(new java.awt.Color(25, 29, 74));
        panelMenuHide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuClimbers.setBackground(new java.awt.Color(25, 29, 74));
        panelMenuClimbers.setLayout(new java.awt.BorderLayout());

        panelClimbersMain.setBackground(new java.awt.Color(25, 29, 74));
        panelClimbersMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersMain.setPreferredSize(new java.awt.Dimension(220, 50));
        panelClimbersMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText.setText("Climbers");
        labelClimbersText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersMain.add(labelClimbersText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 50));

        labelClimbersIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersMain.add(labelClimbersIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenuClimbers.add(panelClimbersMain, java.awt.BorderLayout.NORTH);

        panelClimbersNew.setBackground(new java.awt.Color(25, 29, 74));
        panelClimbersNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelClimbersNewMouseClicked(evt);
            }
        });
        panelClimbersNew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText1.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText1.setText("New");
        labelClimbersText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersNew.add(labelClimbersText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 50));

        labelClimbersIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersNew.add(labelClimbersIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        panelMenuClimbers.add(panelClimbersNew, java.awt.BorderLayout.CENTER);

        panelClimbersSearch.setBackground(new java.awt.Color(25, 29, 74));
        panelClimbersSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelClimbersSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelClimbersSearchMouseClicked(evt);
            }
        });
        panelClimbersSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText2.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText2.setText("Search");
        panelClimbersSearch.add(labelClimbersText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 50));

        labelClimbersIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelClimbersSearch.add(labelClimbersIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        panelMenuClimbers.add(panelClimbersSearch, java.awt.BorderLayout.PAGE_END);

        panelMenuHide.add(panelMenuClimbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        panelMenuCompetition.setBackground(new java.awt.Color(25, 29, 74));
        panelMenuCompetition.setLayout(new java.awt.BorderLayout());

        panelCompetitonMain.setBackground(new java.awt.Color(25, 29, 74));
        panelCompetitonMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCompetitonMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText3.setBackground(new java.awt.Color(138, 165, 195));
        labelClimbersText3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText3.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText3.setText("Competitions");
        panelCompetitonMain.add(labelClimbersText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 50));

        labelClimbersIcon3.setBackground(new java.awt.Color(138, 165, 195));
        labelClimbersIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCompetitonMain.add(labelClimbersIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelMenuCompetition.add(panelCompetitonMain, java.awt.BorderLayout.PAGE_START);

        panelCompetitonNew.setBackground(new java.awt.Color(25, 29, 74));
        panelCompetitonNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCompetitonNew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText4.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText4.setText("New");
        panelCompetitonNew.add(labelClimbersText4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 50));

        labelClimbersIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCompetitonNew.add(labelClimbersIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        panelMenuCompetition.add(panelCompetitonNew, java.awt.BorderLayout.CENTER);

        panelCompetitonSearch.setBackground(new java.awt.Color(25, 29, 74));
        panelCompetitonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCompetitonSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelClimbersText5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelClimbersText5.setForeground(new java.awt.Color(255, 255, 255));
        labelClimbersText5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClimbersText5.setText("Search");
        panelCompetitonSearch.add(labelClimbersText5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 120, 50));

        labelClimbersIcon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCompetitonSearch.add(labelClimbersIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        panelMenuCompetition.add(panelCompetitonSearch, java.awt.BorderLayout.PAGE_END);

        panelMenuHide.add(panelMenuCompetition, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, -1));

        panelMenu.add(panelMenuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMenu, java.awt.BorderLayout.LINE_START);

        panelMainContent.setBackground(new java.awt.Color(73, 128, 242));
        panelMainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelMainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelClimbersNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClimbersNewMouseClicked
//        System.out.println("adding panel climber!");
//        dashboardPanelHolder.removeAll();
//        dashboardPanelHolder.revalidate();
//        dashboardPanelHolder.repaint();
//        PanelClimber panelClimber = new PanelClimber();
//
//        dashboardPanelHolder.add(panelClimber);
//        panelClimber.setVisible(true);
//        dashboardPanelHolder.setVisible(true);
//        dashboardPanelHolder.repaint();


    }//GEN-LAST:event_panelClimbersNewMouseClicked

    private void panelClimbersSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClimbersSearchMouseClicked
        System.out.println("adding panel search climbers!");

        panelMainContent.removeAll();
        panelMainContent.revalidate();
        panelMainContent.repaint();
        PanelListClimbers panel = new PanelListClimbers();

        panelMainContent.add(panel);
        panel.setVisible(true);
        panelMainContent.setVisible(true);
        panelMainContent.repaint();
    }//GEN-LAST:event_panelClimbersSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBurger;
    private javax.swing.JLabel labelClimbersIcon;
    private javax.swing.JLabel labelClimbersIcon1;
    private javax.swing.JLabel labelClimbersIcon2;
    private javax.swing.JLabel labelClimbersIcon3;
    private javax.swing.JLabel labelClimbersIcon4;
    private javax.swing.JLabel labelClimbersIcon5;
    private javax.swing.JLabel labelClimbersText;
    private javax.swing.JLabel labelClimbersText1;
    private javax.swing.JLabel labelClimbersText2;
    private javax.swing.JLabel labelClimbersText3;
    private javax.swing.JLabel labelClimbersText4;
    private javax.swing.JLabel labelClimbersText5;
    private javax.swing.JLabel labelClose;
    private javax.swing.JLabel labelMaximize;
    private javax.swing.JLabel labelMinimize;
    private javax.swing.JLabel labelSettings;
    private javax.swing.JPanel panelButtonClose;
    private javax.swing.JPanel panelButtonMax;
    private javax.swing.JPanel panelButtonMin;
    private javax.swing.JPanel panelClimbersMain;
    private javax.swing.JPanel panelClimbersNew;
    private javax.swing.JPanel panelClimbersSearch;
    private javax.swing.JPanel panelCompetitonMain;
    private javax.swing.JPanel panelCompetitonNew;
    private javax.swing.JPanel panelCompetitonSearch;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelIconMinMaxClose;
    private javax.swing.JPanel panelMainContent;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenuClimbers;
    private javax.swing.JPanel panelMenuCompetition;
    private javax.swing.JPanel panelMenuHide;
    private javax.swing.JPanel panelMenuIcon;
    // End of variables declaration//GEN-END:variables

    public void menuNewClimberAddMouseClicked(Consumer<MouseEvent> handler) {
        FormActionHelper.addMouseClicked(panelClimbersNew, handler);
    }

    public void menuSearchClimberAddMouseClicked(Consumer<MouseEvent> handler) {
        FormActionHelper.addMouseClicked(panelClimbersSearch, handler);
    }

    public void menuNewCompetitionAddMouseClicked(Consumer<MouseEvent> handler) {
        FormActionHelper.addMouseClicked(panelCompetitonNew, handler);
    }

    public void menuSearchCompetitionAddMouseClicked(Consumer<MouseEvent> handler) {
        FormActionHelper.addMouseClicked(panelCompetitonSearch, handler);
    }
    
    public PanelMainContent getPanelMainContent() {
        return (PanelMainContent) panelMainContent;
    }

    private void prepareForm() {
        
        
        labelClose.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.CLOSE, 50, new Color(255, 255, 255)));
        labelMaximize.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FULLSCREEN, 50, new Color(255, 255, 255)));
        labelMinimize.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.REMOVE, 50, new Color(255, 255, 255)));
        labelBurger.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.MENU, 50, new Color(255, 255, 255)));
        labelSettings.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SETTINGS, 50, new Color(255, 255, 255)));

        FormStyleHelper.styleButtonComponents(Arrays.asList(labelClose, panelButtonClose, labelMaximize, labelMinimize), FormStyleHelper.TITLE_BAR_BUTTONS_ENTER);
        // enter, click, exit
//        mouseEnter(labelClose, panelButtonClose);
//        mouseExited(labelClose, panelButtonClose);
        closeButtonClicked(labelClose);
        /*
        mouseEnter(labelMaximize, panelButtonMax);
        mouseExited(labelMaximize, panelButtonMax);

        mouseEnter(labelMinimize, panelButtonMin);
        mouseExited(labelMinimize, panelButtonMin);
         */
        maxButtonClicked(labelMaximize);

        /*
        style climbers menu
         */
        //mouseEnter(labelClimbersText, panelClimbersMain);
        //mouseExited(labelClimbersText, panelClimbersMain);
//        FormStyleHelper.styleButtonComponent(panelClimbersMain, FormStyleHelper.MENU_ENTER_COLOR);
//        FormStyleHelper.styleButtonComponent(panelClimbersNew, FormStyleHelper.MENU_ENTER_COLOR);
//        FormStyleHelper.styleButtonComponent(panelClimbersSearch, FormStyleHelper.MENU_ENTER_COLOR);
        FormStyleHelper.styleButtonComponents(Arrays.asList(panelClimbersMain,
                panelClimbersNew,
                panelClimbersSearch,
                panelCompetitonMain,
                panelCompetitonNew,
                panelCompetitonSearch
        ),
                FormStyleHelper.MENU_ENTER_COLOR);

        FrameDragListener.addDragCapability(panelHeader);

        labelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(evt.getComponent());
                topFrame.setExtendedState(JFrame.ICONIFIED);
            }
        });

//        panelDashboardView.add(new PanelDashboardImage());
    }

    private void mouseEnter(JLabel labelButton, JPanel panelButton) {

        labelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changecolor(panelButton, new Color(25, 29, 74));

            }
        });

    }

    private void mouseExited(JLabel labelButton, JPanel panelButton) {

        labelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changecolor(panelButton, new Color(5, 10, 46));

            }
        });

    }

    // todo refactor
    private void closeButtonClicked(JLabel labelButton) {

        labelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });

    }

    // todo refactor
    private void maxButtonClicked(JLabel labelButton) {

        labelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(evt.getComponent());
                if (topFrame.getExtendedState() != JFrame.MAXIMIZED_BOTH) {
                    topFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    labelButton.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FULLSCREEN_EXIT, 50, new Color(255, 255, 255)));

                } else {
                    topFrame.setExtendedState(JFrame.NORMAL);
                    labelButton.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FULLSCREEN, 50, new Color(255, 255, 255)));

                }
            }
        });

    }

    private void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
}
