/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dostojic.climbers.view.form.competition;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Dejan.Ostojic
 */
public class PanelRegistrations extends javax.swing.JPanel {

    /**
     * Creates new form PanelRegistrations
     */
    public PanelRegistrations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTableRegistrations = new javax.swing.JPanel();
        panelRegistrationsFilter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFilterClimberName = new javax.swing.JTextField();
        buttonFilterRegisrations = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistrations = new javax.swing.JTable();
        buttonAddRegistration = new javax.swing.JButton();
        buttonUpdateRegistration = new javax.swing.JButton();
        buttonDeleteRegistration = new javax.swing.JButton();

        panelTableRegistrations.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrations"));
        panelTableRegistrations.setPreferredSize(null);

        panelRegistrationsFilter.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
        panelRegistrationsFilter.setPreferredSize(null);

        jLabel1.setText("Climber name:");

        buttonFilterRegisrations.setText("Filter registrations");

        javax.swing.GroupLayout panelRegistrationsFilterLayout = new javax.swing.GroupLayout(panelRegistrationsFilter);
        panelRegistrationsFilter.setLayout(panelRegistrationsFilterLayout);
        panelRegistrationsFilterLayout.setHorizontalGroup(
            panelRegistrationsFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrationsFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrationsFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrationsFilterLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textFilterClimberName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrationsFilterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonFilterRegisrations)))
                .addContainerGap())
        );
        panelRegistrationsFilterLayout.setVerticalGroup(
            panelRegistrationsFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrationsFilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistrationsFilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFilterClimberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttonFilterRegisrations)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableRegistrations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRegistrations);

        buttonAddRegistration.setText("Add");

        buttonUpdateRegistration.setText("Update");

        buttonDeleteRegistration.setText("Delete");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAddRegistration)
                    .addComponent(buttonUpdateRegistration)
                    .addComponent(buttonDeleteRegistration))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonAddRegistration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateRegistration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteRegistration)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTableRegistrationsLayout = new javax.swing.GroupLayout(panelTableRegistrations);
        panelTableRegistrations.setLayout(panelTableRegistrationsLayout);
        panelTableRegistrationsLayout.setHorizontalGroup(
            panelTableRegistrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableRegistrationsLayout.createSequentialGroup()
                .addGroup(panelTableRegistrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistrationsFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTableRegistrationsLayout.setVerticalGroup(
            panelTableRegistrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableRegistrationsLayout.createSequentialGroup()
                .addComponent(panelRegistrationsFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTableRegistrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTableRegistrations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonAddRegistration() {
        return buttonAddRegistration;
    }

    public JButton getButtonDeleteRegistration() {
        return buttonDeleteRegistration;
    }

    public JButton getButtonFilterRegisrations() {
        return buttonFilterRegisrations;
    }

    public JButton getButtonUpdateRegistration() {
        return buttonUpdateRegistration;
    }

    public JTable getTableRegistrations() {
        return tableRegistrations;
    }

    public JTextField getTextFilterClimberName() {
        return textFilterClimberName;
    }

    
    public void addRegistrationActionListener(ActionListener actionListener) {
        buttonAddRegistration.addActionListener(actionListener);
    }
    
    public void updateRegistrationActionListener(ActionListener actionListener) {
        buttonUpdateRegistration.addActionListener(actionListener);
    }
    
    public void deleteRegistrationActionListener(ActionListener actionListener) {
        buttonDeleteRegistration.addActionListener(actionListener);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddRegistration;
    private javax.swing.JButton buttonDeleteRegistration;
    private javax.swing.JButton buttonFilterRegisrations;
    private javax.swing.JButton buttonUpdateRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelRegistrationsFilter;
    private javax.swing.JPanel panelTableRegistrations;
    private javax.swing.JTable tableRegistrations;
    private javax.swing.JTextField textFilterClimberName;
    // End of variables declaration//GEN-END:variables
}
